[クライアントブラウザ] ---(HTTPS)---> [Amazon S3 (静的ファイル)] ---(HTTPS)---> [Reactアプリ]

[予約フォーム送信] ---(HTTPS)---> [Amazon API Gateway] ---(HTTP)---> [AWS Lambda (Golang)] ---(JDBC)---> [Amazon RDS (MySQL)]

[予約管理者ブラウザ/モバイル] ---(HTTPS)---> [Amazon S3 (静的ファイル)] ---(HTTPS)---> [React管理アプリ]
                                                ---(HTTPS)---> [Amazon API Gateway] ---(HTTP)---> [AWS Lambda (Golang)] ---(JDBC)---> [Amazon RDS (MySQL)]

[認証] ---(HTTPS)---> [Amazon Cognito]
